apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-list
spec:
  selector:
    matchLabels:
      app: to-do-list
  template:
    metadata:
      labels:
        app: to-do-list
    spec:
      containers:
      - name: to-do-list
        image: gabrielnathan/to-do-list:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
